name: Build DockerHub Image

on: [push]

jobs:
  build:
    env:
      AUTHOR: hiteshjasani
      REPO: http-echo
      IMAGE: http-echo
      VERSION: 0.1
      NIM_VERSION: 1.0.2

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Build
      run: docker build -t $AUTHOR/$REPO:$IMAGE-$VERSION .

    - name: Test
      run: docker run --rm $AUTHOR/$REPO:$IMAGE-$VERSION -h

    - name: List docker images
      run: docker images

    - name: Log in to Github Packages
      run: echo $TOKEN | docker login -u $AUTHOR --password-stdin
      env:
        TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Publish image to hub.docker.com
      run: docker push $AUTHOR/$REPO:$IMAGE-$VERSION
